language: rust
rust:
  - stable
  - nightly

os:
  - linux
  - osx
dist: focal

addons:
  apt:
    packages:
      - python3
      - python3-pip
  homebrew:
    packages:
      - python3

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - os: windows
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH:$TRAVIS_BUILD_DIR/target/debug

env:
  - PATH=$PATH:$TRAVIS_BUILD_DIR/target/debug

# install python for Windows
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install -y --no-progress python --version 3.8; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then python -m pip install --upgrade pip; fi

# command to install dependencies
install:
  - pip3 install torch===1.7.0 torchvision===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html --quiet
  - pip3 install --upgrade --ignore-installed --quiet pip setuptools
  - pip3 install -r n3-torch/ffi/python/requirements.txt --quiet
  - cd n3-torch/ffi/python && python setup.py install --user

script:
  # skip 'n3-net-api': dependency 'rocket' requires nightly
  - cargo build --verbose --workspace --exclude n3-net-api
  - cargo test --verbose --workspace --exclude n3-net-api
