language: rust
rust:
  - stable
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

# command to install dependencies
before_install:
  - pip3 install -r n3-torch-ffi-python/requirements.txt

script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
