language: rust
rust:
  - stable
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

# command to install dependencies
install:
  - pip install -r n3-torch-ffi-python/requirements.txt

script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
