language: rust
rust:
  - stable
  - nightly

os:
  - linux
dist: focal

addons:
  apt:
    packages:
      - python3
      - python3-pip
  # homebrew:
  #   packages:
  #     - python3

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

# command to install dependencies
install:
  - pip3 install torch torchvision --quiet
  - pip3 install --upgrade --ignore-installed --quiet pip setuptools
  - pip3 install -r n3-torch/ffi/python/requirements.txt --quiet

script:
  - cargo build --verbose --workspace
  # 'rocket' requires nightly
  - cargo test --verbose --workspace --exclude n3-net-api
