name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Python. Setup version ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Python. Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch===1.7.0+cpu torchvision===0.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html --quiet
        pip install -r n3-torch/ffi/python/requirements.txt --quiet
        pip install -e n3-torch/ffi/python

    - name: Add PATH
      run: echo "$GITHUB_WORKSPACE/target/debug" >> $GITHUB_PATH

    # skip 'n3-net-api': dependency 'rocket' requires nightly
    - name: Rust. Build
      run: cargo build --verbose --workspace --exclude n3-net-api
    - name: Rust. Run tests
      run: cargo test --verbose --workspace --exclude n3-net-api
